import logging
from datetime import datetime

from sqlalchemy import text

from quads.server.models import Base, Engine, Role, User, db, engine_from_config

logger = logging.getLogger(__name__)


def check_db_timezone_consistency(engine=None):
    """Compare the application local timezone with the database session timezone.

    The timestamp helpers in ``quads.helpers.timeutil`` treat every naive
    datetime in the database as application-local wall clock time.  Rows written
    by the database itself (``func.now()`` defaults, which are application-side
    since this change) used the database session wall clock instead, which is
    only equivalent when both sides run in the same timezone.  This check logs a
    warning when they differ so the mislabeling described in issue #709 is not
    silently reintroduced.

    Returns ``True`` when the timezones match, ``False`` when they differ and
    ``None`` when the database could not be queried.
    """
    engine = engine or Engine
    try:
        with engine.connect() as conn:
            db_offset_seconds = conn.execute(text("SELECT EXTRACT(TIMEZONE FROM now())::int")).scalar()
    except Exception as ex:
        logger.warning(f"Could not read the database session timezone: {ex}")
        return None

    app_offset_seconds = int(datetime.now().astimezone().utcoffset().total_seconds())
    if db_offset_seconds == app_offset_seconds:
        logger.info(
            "Database session timezone (%+dmin) matches the application local timezone.",
            db_offset_seconds // 60,
        )
        return True

    db_hours, db_minutes = db_offset_seconds // 3600, (abs(db_offset_seconds) // 60) % 60
    app_hours, app_minutes = app_offset_seconds // 3600, (abs(app_offset_seconds) // 60) % 60
    logger.error(
        f"Database session timezone (UTC{db_hours:+d}:{db_minutes:02d}) differs from the "
        f"application local timezone (UTC{app_hours:+d}:{app_minutes:02d}). Datetimes "
        "generated by the database are mislabeled as GMT. Align the database server and "
        "the application timezone, then rerun this check."
    )
    return False


def init_db(config=None):
    # Import all modules here that might define models so that
    # they will be registered properly on the metadata. Otherwise,
    # you will have to import them first before calling init_db()
    import quads.server.models

    engine = Engine
    if config:
        engine = engine_from_config(config)

    try:
        conn = engine.connect()
        conn.close()
    except Exception:
        import sqlalchemy

        url = engine.url
        default_url = url.set(database="postgres")
        tmp_engine = sqlalchemy.create_engine(default_url)
        conn = tmp_engine.connect()
        conn = conn.execution_options(isolation_level="AUTOCOMMIT")
        conn.execute(text(f"CREATE DATABASE {url.database}"))
        conn.close()
        tmp_engine.dispose()

    Base.metadata.create_all(bind=engine)
    check_db_timezone_consistency(engine)


def drop_all(config=None):
    engine = Engine
    if config:
        engine = engine_from_config(config)
    Base.metadata.drop_all(bind=engine)


def populate(user_datastore):
    admin_role_name = "admin"
    admin_role_description = "Administrative role"

    user_role_name = "user"
    user_role_description = "Regular user role"

    admin_role = create_role(admin_role_name, admin_role_description)
    user_role = create_role(user_role_name, user_role_description)

    regular_user = "gonza@redhat.com"
    admin_user = "grafuls@redhat.com"

    admin_user_added = create_user(user_datastore, admin_user, "password", [admin_role])
    regular_user_added = create_user(user_datastore, regular_user, "password", [user_role])

    if admin_role or user_role or admin_user_added or regular_user_added:
        db.session.commit()


def create_user(user_datastore, email, password, roles):
    user_entry = db.session.query(User).filter(User.email == email).first()

    if not user_entry:
        user_datastore.create_user(email=email, password=password, roles=roles)
        db.session.commit()
        return True
    return False


def modify_user(user_datastore, email, new_password=None):
    user = user_datastore.find_user(email=email)
    if not user:
        return False

    if new_password:
        user.password = new_password
        db.session.commit()
        return True
    return False


def remove_user(user_datastore, email):
    user = user_datastore.find_user(email=email)

    if user:
        user_datastore.delete_user(user)
        db.session.commit()
        return True
    return False


def create_role(name, description):
    role_entry = db.session.query(Role).filter(Role.name == name).first()
    if not role_entry:
        role = Role(name=name, description=description)
        db.session.add(role)
        return role
    return role_entry
