[metadata]
name = quads
description = QUADS automates the future scheduling, end-to-end provisioning and delivery of bare-metal servers and networks.
long_description = file: README.md
long_description_content_type = text/markdown
license = GPLv3
license_files = LICENSE
platforms = any
url = https://quads.dev
classifiers =
    Development Status :: 5 - Production/Stable
    Programming Language :: Python :: 3
    License :: OSI Approved :: GNU General Public License v3 (GPLv3)
    Operating System :: OS Independent
    Programming Language :: Python :: 3.11
keywords = oob, management
project_urls =
    Bug Tracker = https://github.com/redhat-performance/quads/issues
    Documentation = https://github.com/redhat-performance/quads
    Source Code = https://github.com/redhat-performance/quads

[options]
packages = find:
python_requires = >=3.11
install_requires =
    pyyaml>=3.10
    setuptools>=39.0
zip_safe = True

[options.packages.find]
where = src

[options.package_data]
quads =
    templates/*
    web/templates/*
    web/templates/wiki/*
    web/static/css/*
    web/static/js/*
    web/static/image/*

[options.data_files]
/opt/quads/conf =
    conf/*
/opt/quads/templates =
    src/quads/templates/*
/opt/quads/migrations =
    migrations/alembic.ini
    migrations/env.py
    migrations/README
    migrations/script.py.mako
/opt/quads/migrations/versions =
    migrations/versions/071677379d4e_hostname_metadata.py
    migrations/versions/0f6d1a14c8f5_hosts_boot_mode.py
    migrations/versions/0f9009b00429_os_type_for_assignments.py
    migrations/versions/157838206445_added_boot_order_to_assignment.py
    migrations/versions/253ba446570d_self_scheduling.py
    migrations/versions/cb3d1e473790_added_overcloud_to_host.py
    migrations/versions/e9b96f886b77_processor_type_for_gpu.py
/etc/systemd/system =
    systemd/quads-server.service
    systemd/quads-web.service
    systemd/quads-db.service
/etc/nginx/conf.d =
    container/etc/nginx/conf.d/apiv3.conf
    container/etc/nginx/conf.d/apiv3_ssl.conf.example
/etc/logrotate.d =
    conf/logrotate_quads.conf
/etc/postfix/postfix-files.d =
    container/etc/postfix/postfix-files.d/quads.cf

[sdist]
formats = gztar

[bdist_wheel]
universal = true

[options.entry_points]
console_scripts =
    quads = quads.cli.main:main
