/var/log/move-and-rebuild.log {
    weekly
    rotate 3
    size 100M
    compress
    delaycompress
}

/var/log/validate-env.log {
    weekly
    rotate 3
    size 100M
    compress
    delaycompress
}

/var/log/quads-notify.log {
    weekly
    rotate 3
    size 100M
    compress
    delaycompress
}

/var/log/quads-regen-heatmap.log {
    weekly
    rotate 3
    size 100M
    compress
    delaycompress
}
