"""Drop the api_tokens.created_at server-side default

Revision ID: 5c9e3f71ad84
Revises: b03922beaffb
Create Date: 2026-09-02 00:00:00.000000

The original API-token migration (965ac44a95f5) gave ``api_tokens.created_at`` a
server-side ``now()`` default.  The timestamp fix for issue #709 sets every
timestamp default in the application (``datetime.now``) instead, so naive values
stored in the database are always application-local wall clock.  Drop the
residual server default so upgraded installs match fresh ones (which never had
it) and no timestamp is ever generated by the database session.

This replaces an earlier data-shift migration: QUADS now requires the
application and the database to both run in UTC (verified at deploy time with
``flask --app quads.server.app check-timezones``), so no historical rows need to
be re-anchored.
"""

import sqlalchemy as sa
from alembic import op

revision = "5c9e3f71ad84"
down_revision = "b03922beaffb"
branch_labels = None
depends_on = None


def upgrade():
    op.alter_column("api_tokens", "created_at", server_default=None)


def downgrade():
    op.alter_column("api_tokens", "created_at", server_default=sa.func.now())
